name: Quality Check - React

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecutar ESLint
      - name: Run ESLint
        run: npx eslint src --max-warnings=0

      # 5. Ejecutar Prettier (check)
      - name: Check Prettier formatting
        run: npx prettier --check "src/**/*.{js,jsx}"

      # 6. Ejecutar tests
      - name: Run Tests
        run: npm test -- --watchAll=false --ci
